//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Podgotovka.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDo
    {
        public int ID_ToDo { get; set; }
        public string Name { get; set; }
        public string Desk { get; set; }
        public Nullable<int> ID_CountXP { get; set; }
        public Nullable<System.DateTime> DataComplite { get; set; }
        public Nullable<int> ID_Type { get; set; }
        public Nullable<bool> IsDone { get; set; }
        public Nullable<int> ID_User { get; set; }
    
        public virtual CountXP CountXP { get; set; }
        public virtual Type Type { get; set; }
        public virtual User User { get; set; }
    }
}
